# Generated by Django 5.0 on 2023-12-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('avatar', models.ImageField(default='Обложка 5 шт ВБ.png', upload_to='profile_images')),
                ('slug', models.SlugField(max_length=55)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('N', 'Скоро на складе'), ('Y', 'В наличии')], default='N', max_length=1)),
                ('length', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
