# Generated by Django 5.0 on 2023-12-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['id'], 'verbose_name': 'Товары', 'verbose_name_plural': 'Товары'},
        ),
    ]
