# Generated by Django 5.0 on 2023-12-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_item_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='new_photos'),
        ),
    ]
