# Generated by Django 5.0 on 2023-12-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_item_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='length',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
