# Generated by Django 5.0 on 2023-12-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_item_price_alter_item_length_alter_item_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(default=1990),
        ),
    ]
