# Generated by Django 5.0 on 2023-12-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_item_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='publish',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
