# Generated by Django 5.0 on 2023-12-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_itemimage_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
