# Generated by Django 5.0 on 2023-12-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_itemimage_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='avatar',
        ),
    ]
