# Generated by Django 5.0 on 2023-12-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_itemimages_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=0, default=1990, max_digits=8, verbose_name='Цена'),
        ),
    ]
