# Generated by Django 5.0 on 2023-12-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsinorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
